# version: '3.9'

services:

  # minio:
  #   image: minio/minio:latest
  #   container_name: my_minio
  #   environment:
  #     MINIO_ROOT_USER: ${MINIO_ROOT_USER}
  #     MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
  #   ports:
  #     - "9000:9000"  # API Access
  #     - "9001:9001"  # Web UI
  #   volumes:
  #     - minio_data:/data
  #   networks:
  #     - my_network
  #   command: server /data --console-address ":9001"

  mongodb:
    image: bitnami/mongodb:8.0
    container_name: my_mongodb
    environment:
      MONGODB_ROOT_PASSWORD: ${MONGODB_ROOT_PASSWORD}
      MONGODB_USERNAME: ${MONGODB_USERNAME}
      MONGODB_PASSWORD: ${MONGODB_PASSWORD}
      MONGODB_DATABASE: ${MONGODB_DATABASE}
    ports:
      - "${MONGODB_PORT}:27017"
    volumes:
      - mongodb_data:/bitnami/mongodb
    networks:
      - my_network

  # redis:
  #   image: redis:7
  #   container_name: my_redis
  #   # restart: always
  #   ports:
  #     - "${REDIS_PORT}:6379"
  #   volumes:
  #     - redis_data:/data
  #   networks:
  #     - my_network
  #   # command: redis-server --requirepass $${REDIS_PASSWORD}  # Use $$ to escape $
  
volumes:
  # minio_data:
  mongodb_data:
  # redis_data:


networks:
  my_network:
    driver: bridge